version: 2
jobs:
  #  build and test jobs go here
  deploy-job:
    docker:
      - image: circleci/ruby:latest-browsers
    working_directory: /tmp/kuuttiminer
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync site/ s3://thesealsaver.com/ --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master
